name: youtube_download_manager
description: "YouTube İndirme Yöneticisi - Videoları arayın, kalite seçin ve indirin."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  path_provider: ^2.1.2
  open_filex: ^4.4.0
  youtube_explode_dart: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
